name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 64000
        script: |
          if [ ! -d "/var/www/html/cicd/2305045" ]; then
            mkdir -p /var/www/html/cicd/2305045
            echo "Folder 2305045 dibuat!"
          fi
          cd /var/www/html/cicd/2305045
          git pull origin main
          # Tambahkan perintah deploy lainnya jika diperlukan
